name: Daily snapshot (Sheet → data.json)

on:
  schedule:
    - cron: "0 6 * * *"   # 06:00 UTC ≈ 08:00 Paris
  workflow_dispatch: {}

permissions:
  contents: write   # autorise le commit via GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, persist-credentials: true }

      - uses: actions/setup-node@v4
        with: { node-version: "20" }

      - name: Generate data.json from Google Sheet (+CMC)
        env:
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
        run: node fetch_and_build.js

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: daily snapshot (Sheet → data.json)"
          file_pattern: data.json
